### ISSUE TITLE
WebDriver and Selenium Notation Update

### ISSUE THREAD

**Issue by acidicgaseouscloud** [bumatic/bitchute-scraper#1]
Hey! 

I wanted to use the package there seems to be in issue with the WebDriver ("'WebDriver' object has no attribute 'find_elements_by_xpath'").  I looked it up and it seems the Selenium [changed their notation](https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el)? 

Is there any way you could fix it / let me know if I made a mistake in calling?

Have a nice day!

**Comment by bumatic** [comment]
Thanks for raising the issue. I just accepted your pull request for now as a short term fix. But in the next step it would be necessary to make the scraper work with the newest version of Selenium.

**Comment by ropcat** [comment]
Hi there - just to let you know, I submitted a PR for maintainer’s review earlier today proposing fixes to bring the code into line with the latest v of Selenium. Hopefully this addresses this issue 😊

**Comment by bumatic** [comment]
Thanks! Accepted the PR and published an updated version 0.1.8 to PyPi.
